"use client";
import { useEffect,useRef } from 'react';
import { C,clamp,grid,shotVector,arrowHead,segmentBox } from './engine';
import type { Snapshot,Player } from './engine';
import type { Connection } from './client';
import { sound } from './audio';
type Point={x:number;y:number};
export default function Arena({connection,state}:{connection:Connection;state:Snapshot}){const canvas=useRef<HTMLCanvasElement>(null),latest=useRef(state);latest.current=state;
useEffect(()=>{const el=canvas.current;if(!el)return;const ctx=el.getContext('2d');if(!ctx)return;const sprites=new Image();sprites.src='/art/balloons.png';const sky=new Image();sky.src='/art/sky.png';let frame=0,last=performance.now(),seq=latest.current.players.find(p=>p.id===connection.id)?.seq||0,lastInput=0,lastAim=0,seen=0,prevCountdown=4;let scale=1,ox=0,oy=0,w=0,h=0;const keys=new Set<string>(),smooth=new Map<string,Point>();let joystick:{id:number;origin:Point;current:Point}|null=null,aim:{id:number;origin:Point;current:Point}|null=null;let predicted:Point|null=null,lastServer:Point|null=null;const particles:{x:number;y:number;vx:number;vy:number;life:number;color:string}[]=[],floaters:{x:number;y:number;text:string;life:number}[]=[];let latestPacket:Snapshot|null=null,rxAt=performance.now();
const current=()=>connection.state||latest.current;const me=()=>current().players.find(p=>p.id===connection.id);const world=(e:PointerEvent):Point=>{const b=el.getBoundingClientRect();return {x:(e.clientX-b.left-ox)/scale,y:(e.clientY-b.top-oy)/scale};};const canPlay=()=>innerWidth>=innerHeight&&!document.hidden&&connection.status==='online'&&(current().phase==='playing'||current().phase==='sudden');
function resize(){const rect=el!.getBoundingClientRect();w=rect.width;h=rect.height;const dpr=Math.min(devicePixelRatio,2);el!.width=w*dpr;el!.height=h*dpr;scale=Math.min(w/C.width,h/C.height);ox=(w-C.width*scale)/2;oy=(h-C.height*scale)/2;ctx!.setTransform(dpr,0,0,dpr,0,0);}
const observer=new ResizeObserver(resize);observer.observe(el);resize();
function down(e:PointerEvent){sound.unlock();if(!canPlay())return;const p=me();if(!p||p.deadUntil)return;const q=world(e);el!.setPointerCapture(e.pointerId);if(q.x<280&&q.y>440&&!joystick){joystick={id:e.pointerId,origin:q,current:q};return;}if(p.role==='builder'){// Right-thumb grid mirrors the actual wall: same slot order for both crews.
const col=Math.floor((q.x-1080)/48),row=Math.floor((q.y-380)/48);if(col>=0&&col<3&&row>=0&&row<6){connection.send({type:'place',slot:row*3+col});return;}for(let s=0;s<18;s++){const g=grid(p.team!,s);if(Math.abs(q.x-g.x)<23&&Math.abs(q.y-g.y)<23){connection.send({type:'place',slot:s});return;}}}else if(!aim&&p.ammo>0){const pos=predicted||p,bow={x:1110,y:540};if(Math.hypot(q.x-bow.x,q.y-bow.y)<125||Math.hypot(q.x-pos.x,q.y-pos.y)<80){aim={id:e.pointerId,origin:q,current:q};connection.send({type:'aim'});sound.fx('tension');}}}
function move(e:PointerEvent){const q=world(e);if(joystick?.id===e.pointerId)joystick.current=q;if(aim?.id===e.pointerId){aim.current=q;if(performance.now()-lastAim>=100){connection.send({type:'aim'});lastAim=performance.now();}}}
function up(e:PointerEvent){if(joystick?.id===e.pointerId){joystick=null;connection.send({type:'input',x:0,y:0,seq:++seq});}if(aim?.id===e.pointerId){if(e.type!=='pointercancel'&&canPlay()){connection.send({type:'shoot',dx:aim.origin.x-aim.current.x,dy:aim.origin.y-aim.current.y});sound.vibrate(8);}aim=null;}}
function reset(){keys.clear();joystick=null;aim=null;connection.send({type:'input',x:0,y:0,seq:++seq});}const keyDown=(e:KeyboardEvent)=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();keys.add(e.key);}},keyUp=(e:KeyboardEvent)=>keys.delete(e.key);el.addEventListener('pointerdown',down);el.addEventListener('pointermove',move);el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up);window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',reset);window.addEventListener('orientationchange',reset);document.addEventListener('visibilitychange',reset);
function text(t:string,x:number,y:number,size=16,color='#fff6d8',align:CanvasTextAlign='center'){ctx!.font=`800 ${Math.max(size,11/scale)}px Arial`;ctx!.textAlign=align;ctx!.lineWidth=4;ctx!.strokeStyle='#12313fa8';ctx!.strokeText(t,x,y);ctx!.fillStyle=color;ctx!.fillText(t,x,y);}
function box(x:number,y:number,team:string,reward:boolean,alpha=1){ctx!.save();ctx!.globalAlpha=alpha;ctx!.translate(x,y);ctx!.fillStyle='#bb7840';ctx!.strokeStyle='#543d2b';ctx!.lineWidth=3;ctx!.beginPath();ctx!.roundRect(-21,-21,42,42,5);ctx!.fill();ctx!.stroke();ctx!.strokeStyle='#e1ad66';ctx!.lineWidth=5;ctx!.strokeRect(-15,-15,30,30);ctx!.beginPath();ctx!.moveTo(-13,13);ctx!.lineTo(13,-13);ctx!.stroke();ctx!.fillStyle=team==='blue'?'#4bd1ff':'#ff765b';ctx!.fillRect(-19,-19,38,5);if(reward)text('↟',0,9,23,'#ffefb6');ctx!.restore();}
function bow(x:number,y:number,angle:number,pull=0,big=false){ctx!.save();ctx!.translate(x,y);ctx!.rotate(angle);const n=big?1.8:1;ctx!.scale(n,n);ctx!.strokeStyle='#fff0b4';ctx!.lineWidth=big?4:3;ctx!.beginPath();ctx!.moveTo(0,-26);ctx!.quadraticCurveTo(25,0,0,26);ctx!.stroke();ctx!.strokeStyle='#533c2a';ctx!.lineWidth=2;ctx!.beginPath();ctx!.moveTo(0,-26);ctx!.lineTo(-pull/2,0);ctx!.lineTo(0,26);ctx!.stroke();ctx!.restore();}
function render(now:number){const dt=Math.min((now-last)/1000,.04);last=now;const s=current(),p=me();if(latestPacket!==s){latestPacket=s;rxAt=connection.receivedAt||now;if(p){if(!predicted||p.deadUntil||!lastServer||Math.hypot(p.x-lastServer.x,p.y-lastServer.y)>120)predicted={x:p.x,y:p.y};else{predicted.x+=(p.x-predicted.x)*.35;predicted.y+=(p.y-predicted.y)*.35;}lastServer={x:p.x,y:p.y};}}
const gameNow=s.now+Math.min((now-rxAt)/1000,.15);let ix=(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0),iy=(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0);if(joystick){ix=(joystick.current.x-joystick.origin.x)/65;iy=(joystick.current.y-joystick.origin.y)/65;}const len=Math.max(1,Math.hypot(ix,iy));ix/=len;iy/=len;if(!canPlay())ix=iy=0;if(now-lastInput>50){connection.send({type:'input',x:ix,y:iy,seq:++seq});lastInput=now;}if(predicted&&p&&!p.deadUntil&&canPlay()){predicted.x=clamp(predicted.x+ix*C.speed*dt,45,C.width-45);predicted.y=clamp(predicted.y+iy*C.speed*dt,100,C.height-100);}
if(!canPlay()){joystick=null;aim=null;}for(const ev of s.events){if(ev.id<=seen)continue;seen=ev.id;if(gameNow-ev.at>1)continue;if(['pop','break','shot','build','respawn','win','countdown','fight'].includes(ev.type))sound.fx(ev.type==='win'?(ev.team===p?.team?'win':'lose'):ev.type==='fight'?'win':ev.type);if(ev.type==='builder'&&ev.player===connection.id){floaters.push({x:640,y:300,text:"YOU’RE THE BUILDER!",life:2});sound.fx('reward');}if(ev.type==='pop'){if(ev.killer===connection.id)sound.fx('laugh',Number(ev.personality));if(ev.player===connection.id)sound.vibrate(35);floaters.push({x:Number(ev.x),y:Number(ev.y),text:'+1 POP!',life:1});}if(ev.type==='break'&&ev.reward&&ev.player===connection.id){sound.fx('reward');floaters.push({x:p?.x||640,y:p?.y||360,text:'+3 ARROWS',life:1});}if(ev.type==='pop'||ev.type==='break'){let x=Number(ev.x),y=Number(ev.y);if(ev.type==='break'){const g=grid(ev.team as 'blue'|'red',Number(ev.slot));x=g.x;y=g.y;if(ev.player===connection.id)floaters.push({x,y:y-25,text:'BOX BROKEN',life:.8});}for(let i=0;i<12&&particles.length<120;i++)particles.push({x,y,vx:(Math.random()-.5)*260,vy:(Math.random()-.5)*260,life:.6,color:ev.type==='break'?'#e3b476':'#ffd765'});}}
sound.mode=s.phase==='sudden'?'sudden':s.endAt-gameNow<30?'urgent':s.phase==='playing'?'battle':'lobby';ctx!.clearRect(0,0,w,h);ctx!.fillStyle='#31596b';ctx!.fillRect(0,0,w,h);if(sky.complete&&sky.naturalWidth){const zoom=Math.max(w/sky.width,h/sky.height)*1.035,bw=sky.width*zoom,bh=sky.height*zoom;ctx!.drawImage(sky,(w-bw)/2+Math.sin(now/18000)*8,(h-bh)/2,bw,bh);}ctx!.fillStyle='#d3e5dc18';ctx!.fillRect(0,0,w,h);ctx!.save();ctx!.translate(ox,oy);ctx!.scale(scale,scale);
ctx!.setLineDash([6,12]);ctx!.strokeStyle='#fff5d52b';ctx!.beginPath();ctx!.moveTo(640,95);ctx!.lineTo(640,640);ctx!.stroke();ctx!.setLineDash([]);
for(const team of ['blue','red'] as const)for(let slot=0;slot<18;slot++){const g=grid(team,slot),value=s.walls[team][slot];if(value)box(g.x,g.y,team,value===2);else if(p?.role==='builder'&&p.team===team){ctx!.strokeStyle='#fff7d54d';ctx!.lineWidth=1;ctx!.setLineDash([4,4]);ctx!.strokeRect(g.x-21,g.y-21,42,42);ctx!.setLineDash([]);}}
for(const q of s.players){let pos=smooth.get(q.id)||{x:q.x,y:q.y};if(q.id===connection.id&&predicted)pos=predicted;else{const age=Math.min((now-rxAt)/1000,.1),tx=q.x+q.vx*age,ty=q.y+q.vy*age;if(Math.hypot(tx-pos.x,ty-pos.y)>150)pos={x:tx,y:ty};else{pos.x+=(tx-pos.x)*Math.min(1,dt*18);pos.y+=(ty-pos.y)*Math.min(1,dt*18);}}smooth.set(q.id,pos);if(q.deadUntil){if(q.id===connection.id)text(`BACK IN ${Math.max(0,q.deadUntil-gameNow).toFixed(1)}s`,640,395,22);continue;}
const happy=q.happyUntil>gameNow,focused=q.aimUntil>gameNow,spriteIndex=q.role==='builder'?1:happy?3:focused?2:q.personality;ctx!.save();ctx!.translate(pos.x,pos.y);ctx!.rotate(Math.sin(now/550+q.personality)*.04);if(gameNow<q.shieldUntil){ctx!.beginPath();ctx!.arc(0,0,37,0,Math.PI*2);ctx!.fillStyle='#bdeeff30';ctx!.strokeStyle='#ddfbff';ctx!.lineWidth=2;ctx!.fill();ctx!.stroke();}if(sprites.complete&&sprites.naturalWidth)ctx!.drawImage(sprites,spriteIndex*sprites.width/4,q.team==='blue'?0:sprites.height/2,sprites.width/4,sprites.height/2,-43,-43,86,86);ctx!.restore();text(q.name+(q.bot?' [BOT]':''),pos.x,pos.y-47,13,q.team==='blue'?'#cbf4ff':'#ffdfd1');if(q.id===connection.id){text('YOU',pos.x,pos.y+56,11,'#ffdd62');}if(!q.connected)text('RECONNECTING',pos.x,pos.y-64,11);if(q.role==='builder')text('⚒',pos.x+33,pos.y,20,'#ffe28c');else{let angle=q.team==='blue'?0:Math.PI;if(q.id===connection.id&&aim)angle=Math.atan2(aim.origin.y-aim.current.y,aim.origin.x-aim.current.x);bow(pos.x+(Math.cos(angle)*32),pos.y,angle,aim&&q.id===connection.id?Math.min(45,Math.hypot(aim.origin.x-aim.current.x,aim.origin.y-aim.current.y)/3):0);}}
// Cap visual prediction at enemy walls while awaiting the server's hit event.
for(const a of s.arrows){const age=Math.min((now-rxAt)/1000,.08);const enemy=a.team==='blue'?'red':'blue',tip=arrowHead(a.x+a.vx*age,a.y+a.vy*age+.5*C.gravity*age*age,a.vx,a.vy+C.gravity*age);let hit=1;for(let slot=0;slot<18;slot++){if(!s.walls[enemy][slot])continue;const g=grid(enemy,slot);hit=Math.min(hit,segmentBox(a.x,a.y,tip.x,tip.y,g.x,g.y));}let x=a.x+a.vx*age,y=a.y+a.vy*age+.5*C.gravity*age*age;if(hit<1){x=a.x+(tip.x-a.x)*hit-(tip.x-x);y=a.y+(tip.y-a.y)*hit-(tip.y-y);}ctx!.save();ctx!.translate(x,y);ctx!.rotate(Math.atan2(a.vy+C.gravity*age,a.vx));ctx!.strokeStyle='#fff0ba';ctx!.lineWidth=3;ctx!.beginPath();ctx!.moveTo(-23,0);ctx!.lineTo(14,0);ctx!.stroke();ctx!.fillStyle='#fff7dc';ctx!.beginPath();ctx!.moveTo(C.arrowTip,0);ctx!.lineTo(10,-5);ctx!.lineTo(10,5);ctx!.fill();ctx!.globalAlpha=.25;ctx!.strokeStyle=a.team==='blue'?'#71ddff':'#ff8e70';ctx!.lineWidth=4;ctx!.beginPath();ctx!.moveTo(-25,0);ctx!.lineTo(-60,0);ctx!.stroke();ctx!.restore();}
if(aim&&p&&predicted){const dx=aim.origin.x-aim.current.x,dy=aim.origin.y-aim.current.y,v=shotVector(dx,dy);for(let i=1;i<23;i++){const t=i*.065,x=predicted.x+v.vx*t,y=predicted.y+v.vy*t+.5*C.gravity*t*t;if(x<0||x>1280||y>680)break;ctx!.globalAlpha=1-i/25;ctx!.fillStyle='#fff4b0';ctx!.beginPath();ctx!.arc(x,y,3.5,0,Math.PI*2);ctx!.fill();}ctx!.globalAlpha=1;text(`${Math.min(100,Math.round(Math.hypot(dx,dy)/C.draw*100))}%`,1110,640,16,'#ffdc62');}
for(let i=particles.length-1;i>=0;i--){const v=particles[i];v.life-=dt;if(v.life<0){particles.splice(i,1);continue;}v.x+=v.vx*dt;v.y+=v.vy*dt;v.vy+=200*dt;ctx!.globalAlpha=v.life/.6;ctx!.fillStyle=v.color;ctx!.fillRect(v.x,v.y,5,5);}ctx!.globalAlpha=1;for(let i=floaters.length-1;i>=0;i--){const f=floaters[i];f.life-=dt;if(f.life<0){floaters.splice(i,1);continue;}f.y-=45*dt;text(f.text,f.x,f.y,20,'#ffdd5c');}
if(s.phase==='countdown'){const n=Math.max(1,Math.ceil(s.startAt-gameNow));if(n!==prevCountdown){sound.fx('countdown');prevCountdown=n;}ctx!.fillStyle='#16364260';ctx!.fillRect(0,0,1280,720);text('BLUE CREW  vs  RED CREW',640,255,26);text(String(n),640,400,105,'#ffda5b');text(p?.role==='builder'?"YOU’RE THE BUILDER!":'DRAW BACK. LET IT FLY.',640,470,23);}
// Independent touch pointers: the joystick never takes ownership of the bow pointer.
ctx!.globalAlpha=.65;const joy=joystick?.origin||{x:145,y:570};ctx!.fillStyle='#163b4d55';ctx!.strokeStyle='#fff4d475';ctx!.lineWidth=2;ctx!.beginPath();ctx!.arc(joy.x,joy.y,65,0,Math.PI*2);ctx!.fill();ctx!.stroke();ctx!.beginPath();ctx!.arc(joy.x+ix*42,joy.y+iy*42,27,0,Math.PI*2);ctx!.fillStyle='#fff5d466';ctx!.fill();ctx!.globalAlpha=1;text('FLY',145,666,13);if(p?.role==='shooter'){ctx!.fillStyle='#163b4d33';ctx!.beginPath();ctx!.arc(1110,540,94,0,Math.PI*2);ctx!.fill();const a=aim?Math.atan2(aim.origin.y-aim.current.y,aim.origin.x-aim.current.x):p.team==='blue'?0:Math.PI;bow(1110,540,a,aim?Math.min(45,Math.hypot(aim.origin.x-aim.current.x,aim.origin.y-aim.current.y)/3):0,true);text(p.ammo?'PULL BOW · RELEASE TO FIRE':'OUT OF ARROWS',1110,675,12);text(`${p.ammo} ARROWS`,1110,403,18,'#fff0b5');}else if(p){const ready=gameNow-p.buildAt>=C.buildCooldown;text(ready?'TAP TO BUILD':'RECHARGING',1150,357,14);for(let slot=0;slot<18;slot++){const x=1101+(slot%3)*48,y=401+Math.floor(slot/3)*48,value=s.walls[p.team!][slot];if(value)box(x,y,p.team!,value===2,.8);else{ctx!.fillStyle=ready?'#163d4b77':'#163d4b33';ctx!.strokeStyle='#fff6d56b';ctx!.lineWidth=1;ctx!.fillRect(x-21,y-21,42,42);ctx!.strokeRect(x-21,y-21,42,42);text('+',x,y+7,23,'#fff4d1');}}}ctx!.restore();frame=requestAnimationFrame(render);}
frame=requestAnimationFrame(render);return()=>{cancelAnimationFrame(frame);observer.disconnect();el.removeEventListener('pointerdown',down);el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up);el.removeEventListener('pointercancel',up);window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',reset);window.removeEventListener('orientationchange',reset);document.removeEventListener('visibilitychange',reset);};},[connection]);return <canvas ref={canvas} className="battle-canvas" aria-label="Battlefield. Move with WASD or the left joystick. Pull the bow and release to fire. Builders tap wall slots."/>;}
