export type AudioPrefs={music:boolean;sfx:boolean;laughs:boolean;haptics:boolean;musicVolume:number;sfxVolume:number};
export const defaults:AudioPrefs={music:true,sfx:true,laughs:true,haptics:true,musicVolume:.25,sfxVolume:.55};
class GameAudio{ctx:AudioContext|null=null;prefs={...defaults};mode='lobby';beat=0;active=0;timer:ReturnType<typeof setInterval>|null=null;lastLaugh=0;
 unlock(){if(!this.ctx){this.ctx=new AudioContext();this.timer=setInterval(()=>this.music(),170);}void this.ctx.resume();}
 tone(freq:number,duration:number,volume:number,type:OscillatorType='sine',delay=0,end?:number){const ctx=this.ctx;if(!ctx||ctx.state!=='running'||this.active>20)return;this.active++;const o=ctx.createOscillator(),g=ctx.createGain(),at=ctx.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,at);if(end)o.frequency.exponentialRampToValueAtTime(end,at+duration);g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(volume,at+.008);g.gain.exponentialRampToValueAtTime(.001,at+duration);o.connect(g);g.connect(ctx.destination);o.start(at);o.stop(at+duration+.01);o.onended=()=>{this.active--;o.disconnect();g.disconnect();};}
 music(){if(!this.prefs.music||!this.ctx||document.hidden)return;const intense=this.mode==='sudden'||this.mode==='urgent',battle=this.mode!=='lobby',pattern=[0,7,12,7,3,10,15,10,5,12,17,12,7,14,19,14],beat=this.beat++;if(!battle&&beat%2)return;const f=146.83*2**(pattern[Math.floor(beat/(intense?1:2))%16]/12),vol=this.prefs.musicVolume*.1;this.tone(f,.14,vol,'triangle');if(beat%4===0)this.tone(f/2,.28,vol*.8,'sine');if(battle&&beat%2===0)this.tone(90,.07,vol,'triangle',0,35);}
 fx(kind:string,personality=0){if(!this.prefs.sfx)return;const v=this.prefs.sfxVolume*.17;switch(kind){case 'shot':this.tone(900,.16,v,'triangle',0,220);this.tone(1500,.2,v*.12,'sine',.08,600);break;case 'tension':this.tone(190,.06,v*.3,'triangle');break;case 'pop':this.tone(320,.12,v,'sawtooth',0,50);break;case 'break':this.tone(170,.14,v,'square',0,45);break;case 'build':this.tone(270,.09,v,'triangle');this.tone(540,.1,v,'triangle');break;case 'reward':this.tone(660,.13,v);this.tone(880,.18,v,'sine',.09);this.tone(1320,.22,v,'sine',.17);break;case 'respawn':this.tone(250,.23,v,'sine',0,700);break;case 'win':for(let i=0;i<5;i++)this.tone([392,494,587,784,988][i],.4,v,'triangle',i*.12);break;case 'lose':this.tone(250,.6,v,'triangle',0,90);break;case 'laugh':if(!this.prefs.laughs||Date.now()-this.lastLaugh<700)return;this.lastLaugh=Date.now();for(let i=0;i<4;i++)this.tone(170+personality*100+(i%2)*80,.11,v*.55,'triangle',i*.13);break;case 'countdown':this.tone(550,.15,v);break;default:this.tone(500,.07,v*.4,'sine');}}
 vibrate(ms=10){if(this.prefs.haptics)navigator.vibrate?.(ms);}
}
export const sound=new GameAudio();
