import test from 'node:test';
import assert from 'node:assert/strict';
import { makeRoom,addPlayer,chooseTeam,chooseRole,setBotBuilder,step,start,C } from '../game/engine.ts';
import { selectMatch,availableTeam,preference,addMatchmakingBuilders } from '../server/matchmaking.ts';
function room(code='ROOM2',isPublic=false){const r=makeRoom(code,'host',0,isPublic);const host=addPlayer(r,'host','Host');chooseTeam(r,host,'blue');return {r,host};}
test('bot Builders default on while an explicit opt-out remains respected',()=>{
 assert.equal(preference(undefined,undefined).botBuilders,true);
 assert.equal(preference('any',true).botBuilders,true);
 assert.equal(preference('any',false).botBuilders,false);
});
test('private host can add/remove exactly one labeled Builder bot without changing humans',()=>{const {r,host}=room();setBotBuilder(r,host,'blue',true,'bot');const bot=r.players.find(p=>p.bot)!;assert.equal(bot.role,'builder');assert.equal(bot.team,'blue');assert.equal(host.role,'shooter');setBotBuilder(r,host,'blue',true,'duplicate');assert.equal(r.players.length,2);setBotBuilder(r,host,'blue',false,'unused');assert.equal(r.players.length,1);});
test('bot options enforce host, team/room limits, human Builder ownership and lobby phase',()=>{const {r,host}=room();const guest=addPlayer(r,'guest','Guest');assert.throws(()=>setBotBuilder(r,guest,'blue',true,'b'),/host/);chooseRole(r,host,'builder');assert.throws(()=>setBotBuilder(r,host,'blue',true,'b'),/already/);chooseRole(r,host,'shooter');for(let i=0;i<4;i++){const p=addPlayer(r,'p'+i,'P');chooseTeam(r,p,'blue');}assert.throws(()=>setBotBuilder(r,host,'blue',true,'b'),/full/);r.maxPlayers=r.players.length;assert.throws(()=>setBotBuilder(r,host,'red',true,'b'),/full/);r.phase='playing';assert.throws(()=>setBotBuilder(r,host,'red',true,'b'),/before/);});
test('bot Builders obey cooldown, build limit and cannot shoot',()=>{const {r,host}=room();const enemy=addPlayer(r,'enemy','Enemy');chooseTeam(r,enemy,'red');setBotBuilder(r,host,'blue',true,'b1');setBotBuilder(r,host,'red',true,'b2');assert.ok(start(r));step(r,3.1,()=>.5);assert.equal(r.walls.blue.filter(Boolean).length,1);step(r,.25,()=>.5);assert.equal(r.walls.blue.filter(Boolean).length,1);for(let i=0;i<40;i++)step(r,C.buildCooldown+.001,()=>.5);assert.equal(r.walls.blue.filter(Boolean).length,18);assert.equal(r.players.find(p=>p.id==='b1')!.stats.fired,0);});
test('server matchmaking prefers fullest compatible public room; excludes private, training, active and bot mismatch',()=>{const a=room('FIRST',true).r,b=room('FULLR',true).r;addPlayer(b,'p2','P');addPlayer(b,'p3','P');const privateR=room('PRIVT').r,training=room('TRAIN',true).r;training.training=true;const active=room('ACTIV',true).r;active.phase='playing';const bots=room('BOTSS',true).r;bots.botBuilders=true;assert.equal(selectMatch([a,b,privateR,training,active,bots],preference('any',false)),b);assert.equal(selectMatch([a,b,bots],preference('red',true)),bots);});
test('team preference is honored and full teams are skipped without moving existing players',()=>{const {r,host}=room('BLUE5',true);for(let i=0;i<4;i++){const p=addPlayer(r,'x'+i,'X');chooseTeam(r,p,'blue');}assert.equal(availableTeam(r,'blue'),null);assert.equal(availableTeam(r,null),'red');assert.equal(selectMatch([r],preference('blue',false)),undefined);assert.equal(host.team,'blue');assert.throws(()=>preference('green',false));assert.throws(()=>preference('any','yes'));});
test('matching bot mode reserves one Builder slot on each crew',()=>{const r=makeRoom('BOT22','',0,true);r.botBuilders=true;let n=0;addMatchmakingBuilders(r,()=>String(n++));assert.equal(r.players.length,2);assert.deepEqual(r.players.map(p=>[p.team,p.role,p.bot]),[['blue','builder',true],['red','builder',true]]);assert.equal(availableTeam(r,null),'blue');});
test('public matchmaking countdown waits, cancels on disconnect and restarts on roster changes',()=>{const {r}=room('QUEU2',true);for(let i=1;i<4;i++){const p=addPlayer(r,'p'+i,'P');chooseTeam(r,p,i<2?'blue':'red');}step(r,.1);assert.equal(r.phase,'lobby');assert.equal(r.matchmakingSeconds,8);step(r,3);assert.equal(r.matchmakingSeconds,5);r.players[3].connected=false;step(r,.1);assert.equal(r.matchmakingSeconds,null);r.players[3].connected=true;step(r,.1);assert.equal(r.matchmakingSeconds,8);const newP=addPlayer(r,'p4','Late');chooseTeam(r,newP,'red');step(r,2);assert.equal(r.matchmakingSeconds,8);step(r,8.01);assert.equal(r.phase,'countdown');assert.equal(r.players.filter(p=>p.role==='builder').length,2);});
